# Generated by Django 3.0.8 on 2020-07-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inputs', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
        migrations.AlterField(
            model_name='inputmodel',
            name='criteria',
            field=models.CharField(choices=[('b1: Ambulatory: Sample 1 - CCD', 'b1: Ambulatory: Sample 1 - CCD'), ('b1: Ambulatory: Sample 1 - RN', 'b1: Ambulatory: Sample 1 - RN')], max_length=64),
        ),
    ]
