# Generated by Django 3.0.8 on 2020-07-20 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inputs', '0002_auto_20200720_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputmodel',
            name='filename',
            field=models.FileField(upload_to='InspectTool/media/'),
        ),
    ]
