# Generated by Django 3.0.8 on 2020-07-20 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inputs', '0003_auto_20200720_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariableSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment', models.CharField(max_length=64)),
                ('assessment_txt', models.CharField(max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='inputmodel',
            name='filename',
            field=models.FileField(upload_to='media/'),
        ),
    ]
