# Generated by Django 3.0.8 on 2020-07-21 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inputs', '0004_auto_20200720_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_results', models.CharField(choices=[('PASS', 'PASS'), ('FAIL', 'FAIL')], max_length=10)),
                ('assessment_txt_results', models.CharField(choices=[('PASS', 'PASS'), ('FAIL', 'FAIL')], max_length=10)),
            ],
        ),
    ]
