# Generated by Django 3.0.8 on 2020-07-23 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inputs', '0005_resultset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultset',
            name='assessment_txt_results',
        ),
        migrations.RemoveField(
            model_name='variableset',
            name='assessment_txt',
        ),
        migrations.AlterField(
            model_name='variableset',
            name='assessment',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
