# Generated by Django 3.0.8 on 2020-07-23 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inputs', '0007_variableset_goals'),
    ]

    operations = [
        migrations.AddField(
            model_name='variableset',
            name='health_concerns',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='variableset',
            name='plan_of_treatment',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='variableset',
            name='reason_for_referral',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
