# Generated by Django 3.0.8 on 2020-07-26 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inputs', '0010_auto_20200723_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultset',
            name='assessment_txt_results',
            field=models.CharField(choices=[('PASS', 'PASS'), ('FAIL', 'FAIL')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='variableset',
            name='assessment_txt',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='resultset',
            name='assessment_results',
            field=models.CharField(choices=[('PASS', 'PASS'), ('FAIL', 'FAIL')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='resultset',
            name='goals_results',
            field=models.CharField(choices=[('PASS', 'PASS'), ('FAIL', 'FAIL')], default='', max_length=10),
        ),
    ]
