# Generated by Django 3.0.8 on 2020-07-26 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inputs', '0011_auto_20200726_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultset',
            name='goals_txt_results',
            field=models.CharField(choices=[('PASS', 'PASS'), ('FAIL', 'FAIL')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='resultset',
            name='health_concerns_txt_results',
            field=models.CharField(choices=[('PASS', 'PASS'), ('FAIL', 'FAIL')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='resultset',
            name='plan_of_treatment_txt_results',
            field=models.CharField(choices=[('PASS', 'PASS'), ('FAIL', 'FAIL')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='resultset',
            name='reason_for_referral_txt_results',
            field=models.CharField(choices=[('PASS', 'PASS'), ('FAIL', 'FAIL')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='variableset',
            name='goals_txt',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='variableset',
            name='health_concerns_txt',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='variableset',
            name='plan_of_treatment_txt',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='variableset',
            name='reason_for_referral_txt',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
