# Generated by Django 3.0.8 on 2020-10-15 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inputs', '0013_auto_20200726_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='LookupSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_lu', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='inputmodel',
            name='criteria',
            field=models.CharField(choices=[('2015E_b1_Amb_Sample1_CCD', '2015E_b1_Amb_Sample1_CCD'), ('2015E_b1_Amb_Sample1_RN', '2015E_b1_Amb_Sample1_RN'), ('2015E_b1_Amb_Sample2_CCD', '2015E_b1_Amb_Sample2_CCD'), ('2015E_b1_Amb_Sample2_RN', '2015E_b1_Amb_Sample2_RN')], max_length=64),
        ),
    ]
