# Generated by Django 3.0.8 on 2020-10-15 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inputs', '0014_auto_20201015_2043'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResultSet',
        ),
        migrations.RemoveField(
            model_name='variableset',
            name='assessment_txt',
        ),
        migrations.RemoveField(
            model_name='variableset',
            name='goals_txt',
        ),
        migrations.RemoveField(
            model_name='variableset',
            name='health_concerns_txt',
        ),
        migrations.RemoveField(
            model_name='variableset',
            name='plan_of_treatment_txt',
        ),
        migrations.RemoveField(
            model_name='variableset',
            name='reason_for_referral_txt',
        ),
    ]
