# Generated by Django 3.0.8 on 2020-10-15 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inputs', '0015_auto_20201015_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='lookupset',
            name='assessment_txt_lu',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
