# Generated by Django 3.0.8 on 2020-10-15 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inputs', '0017_auto_20201015_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='lookupset',
            name='health_concerns_lu',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='lookupset',
            name='health_concerns_txt_lu',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
