# Generated by Django 3.0.8 on 2020-10-15 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inputs', '0018_auto_20201015_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='lookupset',
            name='plan_of_treatment_lu',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='lookupset',
            name='plan_of_treatment_txt_lu',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
