# Generated by Django 3.0.8 on 2020-10-16 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inputs', '0019_auto_20201015_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='lookupset',
            name='reason_for_referral_lu',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='lookupset',
            name='reason_for_referral_txt_lu',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
