# Generated by Django 3.0.8 on 2020-10-16 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inputs', '0020_auto_20201016_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='lookupset',
            name='functional_status_lu',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='lookupset',
            name='functional_status_txt_lu',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='variableset',
            name='cognitive_status',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='variableset',
            name='functional_status',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
