# Generated by Django 3.0.8 on 2020-10-16 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inputs', '0021_auto_20201016_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='lookupset',
            name='cognitive_status_lu',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='lookupset',
            name='cognitive_status_txt_lu',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
