# Generated by Django 3.0.8 on 2020-10-21 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inputs', '0022_auto_20201016_1751'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LookupSet',
        ),
        migrations.DeleteModel(
            name='VariableSet',
        ),
    ]
