# Generated by Django 3.1.3 on 2021-06-03 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inputs', '0024_auto_20210430_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputmodel',
            name='criteria',
            field=models.CharField(choices=[('2015E_b1_Ambulatory', '2015E_b1_Ambulatory'), ('2015E_b1_Inpatient', '2015E_b1_Inpatient'), ('2015E_b6_Ambulatory', '2015E_b6_Ambulatory'), ('2015E_b6_Inpatient', '2015E_b6_Inpatient'), ('2015E_b7_Ambulatory', '2015E_b7_Ambulatory'), ('2015E_b7_Inpatient', '2015E_b7_Inpatient'), ('2015E_e1_Ambulatory', '2015E_e1_Ambulatory'), ('2015E_e1_Inpatient', '2015E_e1_Inpatient'), ('2015E_g9_Ambulatory', '2015E_g9_Ambulatory'), ('2015E_g9_Inpatient', '2015E_g9_Inpatient')], max_length=64),
        ),
    ]
