# Generated by Django 3.0.8 on 2022-02-09 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inputs', '0026_auto_20211213_0357'),
    ]

    operations = [
        migrations.CreateModel(
            name='IGModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria', models.CharField(choices=[('b.1 Amb: Sample 1 - 2015e', 'b.1 Amb: Sample 1 - 2015e'), ('b.1 Amb: Sample 2 - 2015e', 'b.1 Amb: Sample 2 - 2015e'), ('b.1 Amb: Sample 1 - 2015e (Cures Update)', 'b.1 Amb: Sample 1 - 2015e (Cures Update)'), ('b.1 Amb: Sample 2 - 2015e (Cures Update)', 'b.1 Amb: Sample 2 - 2015e (Cures Update)'), ('b.1 Amb: Sample 3 - 2015e (Cures Update)', 'b.1 Amb: Sample 3 - 2015e (Cures Update)'), ('b.1 Inp: Sample 1 - 2015e', 'b.1 Inp: Sample 1 - 2015e'), ('b.1 Inp: Sample 2 - 2015e', 'b.1 Inp: Sample 2 - 2015e'), ('b.1 Inp: Sample 1 - 2015e (Cures Update)', 'b.1 Inp: Sample 1 - 2015e (Cures Update)'), ('b.1 Inp: Sample 2 - 2015e (Cures Update)', 'b.1 Inp: Sample 2 - 2015e (Cures Update)'), ('b.1 Inp: Sample 3 - 2015e (Cures Update)', 'b.1 Inp: Sample 3 - 2015e (Cures Update)'), ('b.2 Amb: Sample 1 - R1.1 CCD - 2015e (Cures Update)', 'b.2 Amb: Sample 1 - R1.1 CCD - 2015e (Cures Update)'), ('b.2 Amb: Sample 1 - R2.1 CCD - 2015e (Cures Update)', 'b.2 Amb: Sample 1 - R2.1 CCD - 2015e (Cures Update)'), ('b.2 Amb: Sample 1 - R2.1 RN - 2015e (Cures Update)', 'b.2 Amb: Sample 1 - R2.1 RN - 2015e (Cures Update)'), ('b.2 Inp: Sample 1 - R2.1 DS - 2015e (Cures Update)', 'b.2 Inp: Sample 1 - R2.1 DS - 2015e (Cures Update)'), ('b.7 Amb: Sample 1 - 2015e', 'b.7 Amb: Sample 1 - 2015e'), ('b.7 Inp: Sample 1 - 2015e', 'b.7 Inp: Sample 1 - 2015e'), ('b.7 Amb: Sample 1 - 2015e (Cures Update)', 'b.7 Amb: Sample 1 - 2015e (Cures Update)'), ('b.7 Inp: Sample 1 - 2015e (Cures Update)', 'b.7 Inp: Sample 1 - 2015e (Cures Update)'), ('b.9 Amb: Sample 1 - 2015e', 'b.9 Amb: Sample 1 - 2015e'), ('b.9 Inp: Sample 1 - 2015e', 'b.9 Inp: Sample 1 - 2015e'), ('b.9 Amb: Sample 1 - 2015e (Cures Update)', 'b.9 Amb: Sample 1 - 2015e (Cures Update)'), ('b.9 Inp: Sample 1 - 2015e (Cures Update)', 'b.9 Inp: Sample 1 - 2015e (Cures Update)'), ('e.1 Amb: Sample 1 - 2015e', 'e.1 Amb: Sample 1 - 2015e'), ('e.1 Amb: Sample 2 - 2015e', 'e.1 Amb: Sample 2 - 2015e'), ('e.1 Amb: Sample 1 - 2015e (Cures Update)', 'e.1 Amb: Sample 1 - 2015e (Cures Update)'), ('e.1 Amb: Sample 2 - 2015e (Cures Update)', 'e.1 Amb: Sample 2 - 2015e (Cures Update)'), ('e.1 Amb: Sample 3 - 2015e (Cures Update)', 'e.1 Amb: Sample 3 - 2015e (Cures Update)'), ('e.1 Inp: Sample 1 - 2015e', 'e.1 Inp: Sample 1 - 2015e'), ('e.1 Inp: Sample 2 - 2015e', 'e.1 Inp: Sample 2 - 2015e'), ('e.1 Inp: Sample 1 - 2015e (Cures Update)', 'e.1 Inp: Sample 1 - 2015e (Cures Update)'), ('e.1 Inp: Sample 2 - 2015e (Cures Update)', 'e.1 Inp: Sample 2 - 2015e (Cures Update)'), ('e.1 Inp: Sample 3 - 2015e (Cures Update)', 'e.1 Inp: Sample 3 - 2015e (Cures Update)'), ('g.9 Amb: Sample 1 - 2015e', 'g.9 Amb: Sample 1 - 2015e'), ('g.9 Amb: Sample 2 - 2015e', 'g.9 Amb: Sample 2 - 2015e'), ('g.9 Amb: Sample 1 - 2015e (Cures Update)', 'g.9 Amb: Sample 1 - 2015e (Cures Update)'), ('g.9 Amb: Sample 2 - 2015e (Cures Update)', 'g.9 Amb: Sample 2 - 2015e (Cures Update)'), ('g.9 Amb: Sample 3 - 2015e (Cures Update)', 'g.9 Amb: Sample 3 - 2015e (Cures Update)'), ('g.9 Inp: Sample 1 - 2015e', 'g.9 Inp: Sample 1 - 2015e'), ('g.9 Inp: Sample 2 - 2015e', 'g.9 Inp: Sample 2 - 2015e'), ('g.9 Inp: Sample 1 - 2015e (Cures Update)', 'g.9 Inp: Sample 1 - 2015e (Cures Update)'), ('g.9 Inp: Sample 2 - 2015e (Cures Update)', 'g.9 Inp: Sample 2 - 2015e (Cures Update)'), ('g.9 Inp: Sample 3 - 2015e (Cures Update)', 'g.9 Inp: Sample 3 - 2015e (Cures Update)')], max_length=64)),
            ],
        ),
    ]
