# Generated by Django 3.0.8 on 2022-05-10 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inputs', '0029_auto_20220427_1819'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IGModel',
        ),
        migrations.AlterField(
            model_name='curesinputmodel',
            name='criteria',
            field=models.CharField(choices=[('b.1c Amb - Sample 1 (v2)', 'b.1c Amb - Sample 1 (v2)'), ('b.1c Amb - Sample 2 (v2)', 'b.1c Amb - Sample 2 (v2)'), ('b.1c Amb - Sample 3 (v6)', 'b.1c Amb - Sample 3 (v6)'), ('b.1c Inp - Sample 1 (v2)', 'b.1c Inp - Sample 1 (v2)'), ('b.1c Inp - Sample 2 (v2)', 'b.1c Inp - Sample 2 (v2)'), ('b.1c Inp - Sample 3 (v7)', 'b.1c Inp - Sample 3 (v7)'), ('b.2c Amb/Inp - Sample 1 - R1.1 CCD (v6)', 'b.2c Amb/Inp - Sample 1 - R1.1 CCD (v6)'), ('b.2c Amb/Inp - Sample 1 - R2.1 CCD (v8)', 'b.2c Amb/Inp - Sample 1 - R2.1 CCD (v8)'), ('b.2c Amb/Inp - Sample 1 - R2.1 RN (v8)', 'b.2c Amb/Inp - Sample 1 - R2.1 RN (v8)'), ('b.2c Inp - Sample 1 - R2.1 DS (v8)', 'b.2c Inp - Sample 1 - R2.1 DS (v8)'), ('b.7c Amb - Sample 1 (v1)', 'b.7c Amb - Sample 1 (v1)'), ('b.7c Inp - Sample 1 (v1)', 'b.7c Inp - Sample 1 (v1)'), ('b.9c Amb - Sample 1 (v1)', 'b.9c Amb - Sample 1 (v1)'), ('b.9c Inp - Sample 1 (v1)', 'b.9c Inp - Sample 1 (v1)'), ('e.1c Amb - Sample 1 (v2)', 'e.1c Amb - Sample 1 (v2)'), ('e.1c Amb - Sample 2 (v2)', 'e.1c Amb - Sample 2 (v2)'), ('e.1c Amb - Sample 3 (v6)', 'e.1c Amb - Sample 3 (v6)'), ('e.1c Inp - Sample 1 (v3)', 'e.1c Inp - Sample 1 (v3)'), ('e.1c Inp - Sample 2 (v2)', 'e.1c Inp - Sample 2 (v2)'), ('e.1c Inp - Sample 3 (v7)', 'e.1c Inp - Sample 3 (v7)'), ('g.9c Amb - Sample 1 (v2)', 'g.9c Amb - Sample 1 (v2)'), ('g.9c Amb - Sample 2 (v2)', 'g.9c Amb - Sample 2 (v2)'), ('g.9c Amb - Sample 3 (v6)', 'g.9c Amb - Sample 3 (v6)'), ('g.9c Inp - Sample 1 (v2)', 'g.9c Inp - Sample 1 (v2)'), ('g.9c Inp - Sample 2 (v2)', 'g.9c Inp - Sample 2 (v2)'), ('g.9c Inp - Sample 3 (v7)', 'g.9c Inp - Sample 3 (v7)')], max_length=64),
        ),
        migrations.AlterField(
            model_name='inputmodel',
            name='criteria',
            field=models.CharField(choices=[('b.1 Amb - Sample 1 (v14)', 'b.1 Amb - Sample 1 (v14)'), ('b.1 Amb - Sample 2 (v14)', 'b.1 Amb - Sample 2 (v14)'), ('b.1 Inp - Sample 1 (v14)', 'b.1 Inp - Sample 1 (v14)'), ('b.1 Inp - Sample 2 (v14)', 'b.1 Inp - Sample 2 (v14)'), ('b.2 Amb/Inp - Sample 1 - R1.1 CCD (v6)', 'b.2 Amb/Inp - Sample 1 - R1.1 CCD (v6)'), ('b.2 Amb/Inp - Sample 1 - R2.1 CCD (v7)', 'b.2 Amb/Inp - Sample 1 - R2.1 CCD (v7)'), ('b.2 Amb/Inp - Sample 1 - R2.1 RN (v7)', 'b.2 Amb/Inp - Sample 1 - R2.1 RN (v7)'), ('b.2 Inp - Sample 1 - R2.1 DS (v7)', 'b.2 Inp - Sample 1 - R2.1 DS (v7)'), ('b.7 Amb - Sample 1 (v3)', 'b.7 Amb - Sample 1 (v3)'), ('b.7 Inp - Sample 1 (v3)', 'b.7 Inp - Sample 1 (v3)'), ('b.9 Amb - Sample 1 (v14)', 'b.9 Amb - Sample 1 (v14)'), ('b.9 Inp - Sample 1 (v15)', 'b.9 Inp - Sample 1 (v15)'), ('e.1 Amb - Sample 1 (v14)', 'e.1 Amb - Sample 1 (v14)'), ('e.1 Amb - Sample 2 (v14)', 'e.1 Amb - Sample 2 (v14)'), ('e.1 Inp - Sample 1 (v14)', 'e.1 Inp - Sample 1 (v14)'), ('e.1 Inp - Sample 2 (v14)', 'e.1 Inp - Sample 2 (v14)'), ('g.9 Amb - Sample 1 (v14)', 'g.9 Amb - Sample 1 (v14)'), ('g.9 Amb - Sample 2 (v14)', 'g.9 Amb - Sample 2 (v14)'), ('g.9 Inp - Sample 1 (v14)', 'g.9 Inp - Sample 1 (v14)'), ('g.9 Inp - Sample 2 (v14)', 'g.9 Inp - Sample 2 (v14)')], max_length=64),
        ),
    ]
